# Limpieza de datos

In [252]:
import numpy as np
import pandas as pd

In [253]:
# Cargar Datos
datos = pd.read_csv('../data/raw/web_raw.csv')

In [254]:
# Revisar columnas
datos.columns = datos[1:2].values.tolist()
datos = datos[2:].reset_index(drop=True)
datos.columns

MultiIndex([('Vehicle size',),
            (   'Character',),
            (      'Ground',),
            (       'Water',),
            (         'Air',),
            ('Anti-Gravity',),
            ('Acceleration',),
            (      'Weight',),
            (      'Ground',),
            (       'Water',),
            (         'Air',),
            ('Anti-Gravity',),
            (    'Traction',),
            (  'Mini-Turbo',)],
           )

## Separar tablas

Cuatro tablas diferentes vienen apiladas en una sola tabla.

In [255]:
datos

,Vehicle size,Character,Ground,Water,Air,Anti-Gravity,Acceleration,Weight,Ground,Water,Air,Anti-Gravity,Traction,Mini-Turbo
0,Small,NaN,0,0,0,0,5,0,10,10,10,10,5,5
1,Small,NaN,2,2,2,2,4,2,8,8,8,8,4,4
2,Medium,NaN,4,4,4,4,4,3,6,6,6,6,3,4
3,Medium,NaN,4,4,4,4,3,4,6,6,6,6,3,3
4,Medium,NaN,6,6,6,6,3,5,4,4,4,4,2,3
5,Medium,NaN,6,6,6,6,2,6,4,4,4,4,2,2
6,Medium,NaN,8,8,8,8,0,10,2,2,2,2,0,0
7,Large,NaN,8,8,8,8,1,8,2,2,2,2,1,1
8,Large,NaN,10,10,10,10,0,10,0,0,0,0,0,0
9,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics,Bodies' statistics
10,Body,Body,Speed,Speed,Speed,Speed,Acceleration,Weight,Handling,Handling,Handling,Handling,Traction,Mini-Turbo
11,Body,Body,Ground,Water,Air,Anti-Gravity,Acceleration,Weight,Ground,Water,Air,Anti-Gravity,Traction,Mini-Turbo
12,NaN,NaN,3,3,2,4,2,2,2,2,1,3,5,3
13,NaN,NaN,3,4,3,3,3,1,4,4,3,4,3,4
14,NaN,NaN,5,4,4,5,1,3,2,2,1,2,1,1
15,NaN,NaN,3,5,2,3,0,4,0,5,0,0,7,0
16,NaN,NaN,0,5,4,0,7,0,4,5,4,3,4,7
17,NaN,NaN,4,3,3,5,3,1,2,2,1,3,3,3
18,NaN,NaN,3,5,3,3,1,3,1,5,4,1,6,1
19,NaN,NaN,3,3,2,3,5,1,5,5,4,5,0,5
20,NaN,NaN,4,5,4,3,2,2,4,4,4,5,2,3
21,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics,Tires' statistics
22,Tires,Tires,Speed,Speed,Speed,Speed,Acceleration,Weight,Handling,Handling,Handling,Handling,Traction,Mini-Turbo
23,Tires,Tires,Ground,Water,Air,Anti-Gravity,Acceleration,Weight,Ground,Water,Air,Anti-Gravity,Traction,Mini-Turbo
24,NaN,NaN,2,4,2,2,2,2,3,3,3,3,4,2
25,NaN,NaN,2,2,0,2,0,4,0,0,0,0,7,0
26,NaN,NaN,0,4,4,0,6,0,4,4,4,4,3,6
27,NaN,NaN,3,3,3,3,1,2,4,4,4,4,2,1
28,NaN,NaN,4,0,4,4,1,3,3,3,3,3,0,1
29,NaN,NaN,3,3,3,3,0,4,3,3,3,3,2,0
30,NaN,NaN,1,0,3,1,3,1,2,1,3,2,6,3
31,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics,Gliders' statistics
32,Glider,Glider,Speed,Speed,Speed,Speed,Acceleration,Weight,Handling,Handling,Handling,Handling,Traction,Mini-Turbo
33,Glider,Glider,Ground,Water,Air,Anti-Gravity,Acceleration,Weight,Ground,Water,Air,Anti-Gravity,Traction,Mini-Turbo
34,NaN,NaN,1,1,2,1,1,2,1,1,1,1,1,1
35,NaN,NaN,1,1,1,1,2,1,1,1,2,1,1,2
36,NaN,NaN,1,1,2,1,1,2,1,1,1,1,1,1

In [256]:
# Dividiendo las tablas
df_personajes = datos.iloc[0:9]
df_vehiculos = datos.iloc[9:21]
df_ruedas = datos.iloc[21:31]
df_planeadores = datos.iloc[31:]

## Corregir Encabezados
Vienen en multinivel. Los dejare con nivel sencillo para facilitar el manejo.

In [257]:
df_personajes.columns =[
            'Size',
            'Character',
            'Speed_Ground',
            'Speed_Water',
            'Speed_Air',
            'Speed_AntiGravity',
            'Acceleration',
            'Weight',
            'Handling_Ground',
            'Handling_Water',
            'Handling_Air',
            'Handling_AntiGravity',
            'Traction',
            'Mini_Turbo'
    ]

In [258]:
df_vehiculos.columns = [
       'Body',
       'Body.2',
       'Speed_Ground',
       'Speed_Water',
       'Speed_Air',
       'Speed_AntiGravity',
       'Acceleration',
       'Weight',
       'Handling_Ground',
       'Handling_Water',
       'Handling_Air',
       'Handling_AntiGravity',
       'Traction',
       'Mini_Turbo'
]

In [259]:
df_ruedas.columns = [
        'Tires',
        'Tires.2',
        'Speed_Ground',
        'Speed_Water',
        'Speed_Air',
        'Speed_AntiGravity',
        'Acceleration',
        'Weight',
        'Handling_Ground',
        'Handling_Water',
        'Handling_Air',
        'Handling_AntiGravity',
        'Traction',
        'Mini_Turbo'
]

In [260]:
df_planeadores.columns = [
        'Glider',
        'Glider.2',
        'Speed_Ground',
        'Speed_Water',
        'Speed_Air',
        'Speed_AntiGravity',
        'Acceleration',
        'Weight',
        'Handling_Ground',
        'Handling_Water',
        'Handling_Air',
        'Handling_AntiGravity',
        'Traction',
        'Mini_Turbo'
]

In [261]:
# Eliminando la fila sobrante que queda despues del ajuste 
# Y reiniciando inddices
df_vehiculos = df_vehiculos[3:].reset_index(drop=True)
df_ruedas = df_ruedas[3:].reset_index(drop=True)
df_planeadores = df_planeadores[3:].reset_index(drop=True)

## Corrigiendo Error de Columnas Duplicadas

La tabla personajes tiene dos columnas iniciales: Tamaño del vehiculo y personje.
El resto de tabla no tiene esa division de tamaño. 

Las cuatro tablas estaban contenidas dentro de la primera. Para no romper el formato, las ultimas tres tablas tenian sus primeras dos columnas combinadas.

**Objetivo:**
- Convertir las dos primeras columnas de cada tablas en una sola.

In [262]:
df_vehiculos = df_vehiculos.drop('Body.2', axis=1)
df_ruedas = df_ruedas.drop('Tires.2', axis=1)
df_planeadores = df_planeadores.drop('Glider.2', axis=1)

## Rellenando Valores Perdidos
En la tabla original, los valores de las columnas primera y segunda estaban como imagenes.
Pondre su equivalente en texto.


**Nota:**  
Hay varios Personajes, Ruedas, Planeadores y Vehiculos, que comparten exactamente las mismas estdisticas y esatn agrupados.
Para simplificar la lectura tomare un nombre para cada grupo y en el Readme.txt estaran todos señalados.

In [263]:
df_personajes['Character'] = [
    'Babies',
    'ShyGuy',
    'CatPeach',
    'Yoshi',
    'Villager',
    'Mario',
    'GoldPeach',
    'Rosalina',
    'Bowser'
]

/var/folders/w3/t1s5tm210s17yf14zsvnbzv80000gn/T/ipykernel_32489/730920951.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_personajes['Character'] = [

In [264]:
df_vehiculos['Body'] = [
    'TeddyBuggy',
    'WildWiggler',
    'BDasher',
    'TriSpeeder',
    'BiddyBuggy',
    'BlueFalcon',
    'TanookiKart',
    'YoshiBike',
    'HylianBike'
]

In [265]:
df_ruedas['Tires'] = [
    'Standard',
    'Monster',
    'Button',
    'Slim',
    'Slick',
    'Metal',
    'Wood'
]

In [266]:
df_planeadores['Glider'] = [
    'Paper',
    'Cloud',
    'Plane'
]

# Guardar Dataframes

In [269]:
df_personajes.to_csv('../data/raw/personajes.csv', index=False)
df_vehiculos.to_csv('../data/raw/vehiculos.csv', index=False)
df_ruedas.to_csv('../data/raw/ruedas.csv', index=False)
df_planeadores.to_csv('../data/raw/planeadores.csv', index=False)